before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: gCF6dpTadBVKhcKbFMbAu2wBc/1jYk1Z2f8IP/6TSDfMssbAk/TQJ0rw0oNVnkiwhEaEF/alqBWHOgQntq0HPGdkeCO/zCU7mPFJPPqBzO8XbF769YK2kh4D4BcTo35gB1VB7bH4qbalPenLhr8pvzdG+4sc848FQke5hKCinxEY3nMe4tULrAa8J+xPuFAJTWOg5E7j5TdWRBq6oTKWm4R5eW5prGtTbCzpgkA0C/tyExkwKimN5FkkBqy7eQZoC+p5cChk1bWsqYUZma/foVXOgIorPSJgJb3/g2YoaXARM1vQGYTf6qTIE1j7wXVreB0MeMtmHW9VVPCh+qJYRgVAad7CSufy/yadG5YkSYGJej/rDNOekkFFyV0mwtXeTFZy0AkcUq5CDwDn0xYvwFxqBvDetKNY8Yk70e1zAxpyP/cZZwJMdgd8HPbL5BpQgdS99qGPfrQreuBWkATGjnEAiDhZDOvO9zMJr3t/bir53FpXHapJuIIjKCer5n3/TWTAPrnggBCJLs/GyYiWcrpQIuZ+NZwnFLqRxo2HNM+wBmySmfeUlcFcdbshciCcN27oQPE5i1Aos46Y5A7RFq4cXavdw+YLesqmk4lxQUrnkodZ0QaSkgjNLy9SNyR+vG2Q18kbbJc9jdWJLBLUtyspYDyJls61dRgkjWCPo9g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
